### PR TITLE
Port telepathy static bindings to TelepathyGLib

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed to 6a7e56b.  Was this tested with collaboration?

For your interest, eventually we'd like to also port to CollabWrapper and DBus.

Added to Port to TelepathyGLib project.

**Comment by chimosky** [comment]
> Was this tested with collaboration?

Tested but not with collaboration

> For your interest, eventually we'd like to also port to CollabWrapper and DBus.

Working on CollabWrapper.

**Comment by quozl** [comment]
> not with collaboration

What is your test environment?

**Comment by chimosky** [comment]
I basically run the activity, and i also use gdb sometimes.
What other ways can testing be done?. and this will most likely be dependent on the activity.

**Comment by quozl** [comment]
By environment I mean your equipment, virtual machines, operating system, and Sugar.  I'm trying to figure out how to enable your testing with collaboration.  Simplest might be two virtual machines on a bridged virtual network.

**Comment by chimosky** [comment]
I'm running arch linux, and i don't use vm at the moment.

**Comment by quozl** [comment]
Okay, your options are;

* multiple Sugar instances on the same computer,
* virtual machines,
* separate computers on a network.

Give the first option a try.  

* [install rdesktop, create an account, and use rdesktop to log in](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md#packaged-sugar),
* then repeat the above using a second account; e.g. I used _sugar_ and then _ragus_,
* have both instances of rdesktop running at once,
* try the F1 through to F4 keys; if they don't work well for you, then use <kbd>alt</kbd><kbd>shift</kbd><kbd>m</kbd> to call up My Settings, and set the Frame Activation Area to about 40px, and use the mouse to show Neighbourhood view; verify that both instances of Sugar are shown as icons in the view.
* if you have many icons in the view, you might be using a Jabber server; you can turn that off in My Settings, Network, by deleting the host name.

Now you're ready to test collaboration.  My favourite is to test [Chat](https://help.sugarlabs.org/en/chat.html).

**Comment by chimosky** [comment]
How do you run rdesktop, I'm finding it a little bit difficult to run it - the command it sugar docs doesn't work for me -

**Comment by quozl** [comment]
I ran it exactly as shown.  It works for me.  How did it not work for you?  i.e. when you type the command, what is the result?

**Comment by chimosky** [comment]
I get this error
``` Autoselected keyboard map en-us
ERROR: 127.0.0.1: unable to connect
```

**Comment by quozl** [comment]
Presumably that error was from the `rdesktop` command, as it is the only one that mentions that IP address.

You should check these things;
* `ip addr show lo` shows that the `lo` network interface has an IPv4 address of, say, 127.0.0.1/8,
* `/usr/sbin/xrdp` is installed,
* a process is running `/usr/sbin/xrdp`; e.g. `pgrep --full /usr/sbin/xrdp$` shows a process ID,
* the process is listening on TCP port 3389 on any address; e.g. `lsof -p $(pgrep --full /usr/sbin/xrdp$) | grep 3389` shows LISTEN,
* you have no `iptables` rules that block connections on TCP port 3389 of interface `lo`.

If any of these things are not true, stop at that point in the list to resolve.  These are not problems with Sugar, so you should use all available resources to resolve them; such as your Linux distribution community, etc.

**Comment by chimosky** [comment]
@quozl please test as i still don't have a remote desktop set up, so this can move forward. Thanks.

**Comment by quozl** [comment]
No, won't test or review until tested by you.  I'm not willing to be a part of your edit and test cycle; that's inefficient.  The activity is not in my critical list, so I don't need to do this activity myself.

You don't need rdesktop, you can also use
* Xvnc,
* multiple logins with gdm3,
* multiple X servers on the same physical display, using startx and ctrl-alt-f1 through to f7,
* Xnest,  or;
* Xephyr to wrap a Sugar instance inside an existing X server.

**Comment by chimosky** [comment]
@quozl tested, Activity works fine.

**Comment by quozl** [comment]
Thanks.  Tested 4076ba69c529888436e39dc8067e89529140746c (before port), and 6a7e56b5055d163b464a6ea3b40ea58c159bb0b4 (after port).  Doesn't work; https://github.com/sugarlabs/slider-puzzle-branch/issues/5.  Won't merge until it works.

Suggestion: never do a port without first testing the existing code works, and if it doesn't then fix it first before the port.

**Comment by Aniket21mathur** [comment]
Is there still a need to keep this pr in "In progress" list of the "Port to TelepathyGLib" project.Thanks!

**Comment by quozl** [comment]
Certainly not, and thanks for noticing.

**Pull request merged**
